import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
	safeArea: {
		flex: 1,
		backgroundColor: '#123B67',
	},
	backgroundShapeTop: {
		position: 'absolute',
		top: -110,
		right: -80,
		width: 280,
		height: 280,
		borderRadius: 140,
		backgroundColor: '#1F6592',
		opacity: 0.65,
	},
	backgroundShapeBottom: {
		position: 'absolute',
		bottom: -145,
		left: -100,
		width: 310,
		height: 310,
		borderRadius: 155,
		backgroundColor: '#0A2B4D',
		opacity: 0.8,
	},
	content: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		paddingHorizontal: 28,
	},
	brandMark: {
		width: 76,
		height: 76,
		borderRadius: 24,
		backgroundColor: '#F4B942',
		alignItems: 'center',
		justifyContent: 'center',
		marginBottom: 24,
		transform: [{ rotate: '-8deg' }],
	},
	brandMarkLine: {
		width: 38,
		height: 6,
		borderRadius: 3,
		backgroundColor: '#123B67',
		marginVertical: 3,
	},
	brandMarkLineShort: {
		width: 25,
		height: 6,
		borderRadius: 3,
		backgroundColor: '#123B67',
		marginVertical: 3,
		alignSelf: 'flex-start',
		marginLeft: 19,
	},
	eyebrow: {
		color: '#F4B942',
		fontSize: 13,
		fontWeight: '800',
		letterSpacing: 2,
		marginBottom: 12,
	},
	title: {
		color: '#FFFFFF',
		fontSize: 34,
		lineHeight: 40,
		fontWeight: '800',
		textAlign: 'center',
		marginBottom: 16,
	},
	description: {
		maxWidth: 340,
		color: '#D9E9F5',
		fontSize: 16,
		lineHeight: 24,
		textAlign: 'center',
	},
	progressArea: {
		width: '100%',
		maxWidth: 340,
		marginTop: 38,
	},
	progressHeader: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginBottom: 10,
	},
	progressLabel: {
		color: '#9FC7E2',
		fontSize: 11,
		fontWeight: '800',
		letterSpacing: 1,
	},
	progressValue: {
		color: '#F4B942',
		fontSize: 12,
		fontWeight: '800',
	},
	progressTrack: {
		width: '100%',
		height: 8,
		borderRadius: 4,
		backgroundColor: '#28557D',
		overflow: 'hidden',
	},
	progressBar: {
		width: '75%',
		height: '100%',
		borderRadius: 4,
		backgroundColor: '#F4B942',
	},
	button: {
		minWidth: 150,
		marginTop: 34,
		paddingVertical: 14,
		paddingHorizontal: 26,
		borderRadius: 12,
		backgroundColor: '#F4B942',
		alignItems: 'center',
	},
	buttonPressed: {
		opacity: 0.75,
	},
	buttonText: {
		color: '#123B67',
		fontSize: 15,
		fontWeight: '800',
	},
	footerText: {
		color: '#9FC7E2',
		fontSize: 12,
		marginTop: 22,
		textAlign: 'center',
	},
});
